### ISSUE TITLE
No license file present

### ISSUE THREAD

**Issue by mikenicholson** [cdtx/mcp2200#1]
There is no license file present in this repo.

This makes using and contributing to this repo ambiguous and risky.  I am evaluating the MCP2200 for an application internal to my company.  Without a license I can play with the code but can't invest any time in contributing back.

**Comment by cdtx** [comment]
You're right
I've just set the MIT license
Cyril

**Comment by mikenicholson** [comment]
Awesome, thanks!  Sorry to be a pedant, we just have to be careful about licensing.
