### ISSUE TITLE
RawDevice instance has no attribute 'set_clear_output'

### ISSUE THREAD

**Issue by mario-chirinos** [cdtx/mcp2200#4]
Traceback (most recent call last):
  File "example.py", line 9, in <module>
    dev.set_clear_output(Set_bmap=0x00, Clear_bmap=0x00)
AttributeError: RawDevice instance has no attribute 'set_clear_output'

**Comment by cdtx** [comment]
dev.set_clear_output**s**(Set_bmap=0x00, Clear_bmap=0x00) should work better
